version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.19

jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: example
        - run: echo "Run your code here"
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws

#      # run tests!
#      - run:
#          name: Run tests with coverage
#          command: npm test --coverage
#
#      - run:
#          name: Deploy application
#          command: sls deploy
