jobs:
  test_my_api:
    executor: aws-servlerless/default
    steps:
      - run: npm run test
  deploy_my_api:
    executor: aws-servlerless/default
      steps:
      - run: serverless deploy
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
version: 2.1
workflows:
  test_and_deploy:
    jobs:
      - test_my_api:
          requires:
            - deploy-staging
      - deploy_my_api:
          name: deploy-production
          requires:
            - test_my_api

#      # run tests!
#      - run:
#          name: Run tests with coverage
#          command: npm test --coverage
#
#      - run:
#          name: Deploy application
#          command: sls deploy
